{"content":"---\ntitle: \"&#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"vbc30382\"\n  - \"bc30382\"\nhelpviewer_keywords: \n  - \"BC30382\"\nms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd\ncaps.latest.revision: 7\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# &#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement\n`Finally` is used to complete a `Try...Catch...Finally` block; hence it can only appear once at the end of the block. Either you have an unnecessary `Finally`, or your `Finally` statement appears outside the bounds of its corresponding `Try` block.  \n  \n **Error ID:** BC30382  \n  \n## To correct this error  \n  \n1.  Locate and remove the unnecessary `Finally`statement.  \n  \n2.  Move the `Finally` statement to the appropriate location in your code.  \n  \n## See Also  \n [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   \n [Structured Exception Handling Overview for Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)","nodes":[{"pos":[12,94],"content":"&#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"&amp;#39;Finally&amp;#39; cannot appear outside a &amp;#39;Try&amp;#39; statement | Microsoft Docs","pos":[0,82],"source":"&#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement | Microsoft Docs"}]},{"pos":[610,675],"content":"&#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement","linkify":"&#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement","nodes":[{"content":"&amp;#39;Finally&amp;#39; cannot appear outside a &amp;#39;Try&amp;#39; statement","pos":[0,65],"source":"&#39;Finally&#39; cannot appear outside a &#39;Try&#39; statement"}]},{"content":"<ph id=\"ph1\">`Finally`</ph> is used to complete a <ph id=\"ph2\">`Try...Catch...Finally`</ph> block; hence it can only appear once at the end of the block.","pos":[676,793],"source":"`Finally` is used to complete a `Try...Catch...Finally` block; hence it can only appear once at the end of the block."},{"content":"Either you have an unnecessary <ph id=\"ph1\">`Finally`</ph>, or your <ph id=\"ph2\">`Finally`</ph> statement appears outside the bounds of its corresponding <ph id=\"ph3\">`Try`</ph> block.","pos":[794,924],"source":" Either you have an unnecessary `Finally`, or your `Finally` statement appears outside the bounds of its corresponding `Try` block."},{"pos":[931,952],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30382","source":"**Error ID:** BC30382"},{"pos":[961,982],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[992,1045],"content":"Locate and remove the unnecessary <ph id=\"ph1\">`Finally`</ph>statement.","source":"Locate and remove the unnecessary `Finally`statement."},{"pos":[1055,1125],"content":"Move the <ph id=\"ph1\">`Finally`</ph> statement to the appropriate location in your code.","source":"Move the `Finally` statement to the appropriate location in your code."},{"pos":[1134,1142],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept><ph id=\"ph1\"> </ph>","pos":[1146,1261],"source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md) "},{"content":"<bpt id=\"p1\"> [</bpt>Structured Exception Handling Overview for Visual Basic<ept id=\"p1\">](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)</ept>","pos":[1264,1392],"source":" [Structured Exception Handling Overview for Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)"}]}