{"content":"---\ntitle: \"Sending and Receiving Faults\"\nms.date: \"03/30/2017\"\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"handling faults [WCF], sending\"\nms.assetid: 7be6fb96-ce2a-450b-aebe-f932c6a4bc5d\n---\n# Sending and Receiving Faults\nSOAP faults convey error condition information from a service to a client and in the duplex case from a client to a service in an interoperable way. Typically a service defines custom fault content and specifies which operations can return them. (For more information, see [Defining and Specifying Faults](../../../docs/framework/wcf/defining-and-specifying-faults.md).) This topic discusses how a service or duplex client can send those faults when the corresponding error condition has occurred and how a client or service application handles these faults. For an overview of error handling in Windows Communication Foundation (WCF) applications, see [Specifying and Handling Faults in Contracts and Services](../../../docs/framework/wcf/specifying-and-handling-faults-in-contracts-and-services.md).  \n  \n## Sending SOAP Faults  \n Declared SOAP faults are those in which an operation has a <xref:System.ServiceModel.FaultContractAttribute?displayProperty=nameWithType> that specifies a custom SOAP fault type. Undeclared SOAP faults are those that are not specified in the contract for an operation.  \n  \n### Sending Declared Faults  \n To send a declared SOAP fault, detect the error condition for which the SOAP fault is appropriate and throw a new <xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType> where the type parameter is a new object of the type specified in the <xref:System.ServiceModel.FaultContractAttribute> for that operation. The following code example shows the use of <xref:System.ServiceModel.FaultContractAttribute> to specify that the `SampleMethod` operation can return a SOAP fault with the detail type of `GreetingFault`.  \n  \n [!code-csharp[FaultContractAttribute#4](../../../samples/snippets/csharp/VS_Snippets_CFX/faultcontractattribute/cs/services.cs#4)]\n [!code-vb[FaultContractAttribute#4](../../../samples/snippets/visualbasic/VS_Snippets_CFX/faultcontractattribute/vb/services.vb#4)]  \n  \n To convey the `GreetingFault` error information to the client, catch the appropriate error condition and throw a new <xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType> of type `GreetingFault` with a new `GreetingFault` object as the argument, as in the following code example. If the client is an WCF client application, it experiences this as a managed exception where the type is <xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType> of type `GreetingFault`.  \n  \n [!code-csharp[FaultContractAttribute#5](../../../samples/snippets/csharp/VS_Snippets_CFX/faultcontractattribute/cs/services.cs#5)]\n [!code-vb[FaultContractAttribute#5](../../../samples/snippets/visualbasic/VS_Snippets_CFX/faultcontractattribute/vb/services.vb#5)]  \n  \n### Sending Undeclared Faults  \n Sending undeclared faults can be very useful to quickly diagnose and debug problems in WCF applications, but its usefulness as a debugging tool is limited. More generally, when debugging it is recommended that you use the <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property. When you set this value to true, clients experience such faults as <xref:System.ServiceModel.FaultException%601> exceptions of type <xref:System.ServiceModel.ExceptionDetail>.  \n  \n> [!IMPORTANT]\n>  Because managed exceptions can expose internal application information, setting <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> to `true` can permit WCF clients to obtain information about internal service operation exceptions, including personally identifiable or other sensitive information.  \n>   \n>  Therefore, setting <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> to `true` is only recommended as a way of temporarily debugging a service application. In addition, the WSDL for a method that returns unhandled managed exceptions in this way does not contain the contract for the <xref:System.ServiceModel.FaultException%601> of type <xref:System.ServiceModel.ExceptionDetail>. Clients must expect the possibility of an unknown SOAP fault (returned to WCF clients as <xref:System.ServiceModel.FaultException?displayProperty=nameWithType> objects) to obtain the debugging information properly.  \n  \n To send an undeclared SOAP fault, throw a <xref:System.ServiceModel.FaultException?displayProperty=nameWithType> object (that is, not the generic type <xref:System.ServiceModel.FaultException%601>) and pass the string to the constructor. This is exposed to the WCF client applications as a thrown <xref:System.ServiceModel.FaultException?displayProperty=nameWithType> exception where the string is available by calling the <xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType> method.  \n  \n> [!NOTE]\n>  If you declare a SOAP fault of type string, and then throw this in your service as a <xref:System.ServiceModel.FaultException%601> where the type parameter is a <xref:System.String?displayProperty=nameWithType> the string value is assigned to the <xref:System.ServiceModel.FaultException%601.Detail%2A?displayProperty=nameWithType> property, and is not available from <xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType>.  \n  \n## Handling Faults  \n In WCF clients, SOAP faults that occur during communication that are of interest to client applications are raised as managed exceptions. While there are many exceptions that can occur during the execution of any program, applications using the WCF client programming model can expect to handle exceptions of the following two types as a result of communication.  \n  \n-   <xref:System.TimeoutException>  \n  \n-   <xref:System.ServiceModel.CommunicationException>  \n  \n <xref:System.TimeoutException> objects are thrown when an operation exceeds the specified timeout period.  \n  \n <xref:System.ServiceModel.CommunicationException> objects are thrown when there is some recoverable communication error condition on either the service or the client.  \n  \n The <xref:System.ServiceModel.CommunicationException> class has two important derived types, <xref:System.ServiceModel.FaultException> and the generic <xref:System.ServiceModel.FaultException%601> type.  \n  \n <xref:System.ServiceModel.FaultException> exceptions are thrown when a listener receives a fault that is not expected or specified in the operation contract; usually this occurs when the application is being debugged and the service has the <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property set to `true`.  \n  \n <xref:System.ServiceModel.FaultException%601> exceptions are thrown on the client when a fault that is specified in the operation contract is received in response to a two-way operation (that is, a method with an <xref:System.ServiceModel.OperationContractAttribute> attribute with <xref:System.ServiceModel.OperationContractAttribute.IsOneWay%2A> set to `false`).  \n  \n> [!NOTE]\n>  When an WCF service has the <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property set to `true` the client experiences this as an undeclared <xref:System.ServiceModel.FaultException%601> of type <xref:System.ServiceModel.ExceptionDetail>. Clients can either catch this specific fault or handle the fault in a catch block for <xref:System.ServiceModel.FaultException>.  \n  \n Typically, only <xref:System.ServiceModel.FaultException%601>, <xref:System.TimeoutException>, and <xref:System.ServiceModel.CommunicationException> exceptions are of interest to clients and services.  \n  \n> [!NOTE]\n>  Other exceptions, of course, do occur. Unexpected exceptions include catastrophic failures like <xref:System.OutOfMemoryException?displayProperty=nameWithType>; typically applications should not catch such methods.  \n  \n### Catch Fault Exceptions in the Correct Order  \n Because <xref:System.ServiceModel.FaultException%601> derives from <xref:System.ServiceModel.FaultException>, and <xref:System.ServiceModel.FaultException> derives from <xref:System.ServiceModel.CommunicationException>, it is important to catch these exceptions in the proper order. If, for example, you have a try/catch block in which you first catch <xref:System.ServiceModel.CommunicationException>, all specified and unspecified SOAP faults are handled there; any subsequent catch blocks to handle a custom <xref:System.ServiceModel.FaultException%601> exception are never invoked.  \n  \n Remember that one operation can return any number of specified faults. Each fault is a unique type and must be handled separately.  \n  \n### Handle Exceptions When Closing the Channel  \n Most of the preceding discussion has to do with faults sent in the course of processing application messages, that is, messages explicitly sent by the client when the client application calls operations on the WCF client object.  \n  \n Even with local objects disposing the object can either raise or mask exceptions that occur during the recycling process. Something similar can occur when you use WCF client objects. When you call operations you are sending messages over an established connection. Closing the channel can throw exceptions if the connection cannot be cleanly closed or is already closed, even if all the operations returned properly.  \n  \n Typically, client object channels are closed in one of the following ways:  \n  \n-   When the WCF client object is recycled.  \n  \n-   When the client application calls <xref:System.ServiceModel.ClientBase%601.Close%2A?displayProperty=nameWithType>.  \n  \n-   When the client application calls <xref:System.ServiceModel.ICommunicationObject.Close%2A?displayProperty=nameWithType>.  \n  \n-   When the client application calls an operation that is a terminating operation for a session.  \n  \n In all cases, closing the channel instructs the channel to begin closing any underlying channels that may be sending messages to support complex functionality at the application level. For example, when a contract requires sessions a binding attempts to establish a session by exchanging messages with the service channel until a session is established. When the channel is closed, the underlying session channel notifies the service that the session is terminated. In this case, if the channel has already aborted, closed, or is otherwise unusable (for example, when a network cable is unplugged), the client channel cannot inform the service channel that the session is terminated and an exception can result.  \n  \n### Abort the Channel If Necessary  \n Because closing the channel can also throw exceptions, then, it is recommended that in addition to catching fault exceptions in the correct order, it is important to abort the channel that was used in making the call in the catch block.  \n  \n If the fault conveys error information specific to an operation and it remains possible that others can use it, there is no need to abort the channel (although these cases are rare). In all other cases, it is recommended that you abort the channel. For a sample that demonstrates all of these points, see [Expected Exceptions](../../../docs/framework/wcf/samples/expected-exceptions.md).  \n  \n The following code example shows how to handle SOAP fault exceptions in a basic client application, including a declared fault and an undeclared fault.  \n  \n> [!NOTE]\n>  This sample code does not use the `using` construct. Because closing channels can throw exceptions, it is recommended that applications create a WCF client first, and then open, use, and close the WCF client in the same try block. For details, see [WCF Client Overview](../../../docs/framework/wcf/wcf-client-overview.md) and [Use Close and Abort to release WCF client resources](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md).  \n  \n [!code-csharp[FaultContractAttribute#3](../../../samples/snippets/csharp/VS_Snippets_CFX/faultcontractattribute/cs/client.cs#3)]\n [!code-vb[FaultContractAttribute#3](../../../samples/snippets/visualbasic/VS_Snippets_CFX/faultcontractattribute/vb/client.vb#3)]  \n  \n## See also\n\n- <xref:System.ServiceModel.FaultException>\n- <xref:System.ServiceModel.FaultException%601>\n- <xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType>\n- [Expected Exceptions](../../../docs/framework/wcf/samples/expected-exceptions.md)\n- [Use Close and Abort to release WCF client resources](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md)\n","nodes":[{"pos":[4,205],"embed":true,"restype":"x-metadata","content":"title: \"Sending and Receiving Faults\"\nms.date: \"03/30/2017\"\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"handling faults [WCF], sending\"\nms.assetid: 7be6fb96-ce2a-450b-aebe-f932c6a4bc5d","nodes":[{"content":"Sending and Receiving Faults","nodes":[{"pos":[0,28],"content":"Sending and Receiving Faults","nodes":[{"content":"Sending and Receiving Faults","pos":[0,28]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[212,240],"content":"Sending and Receiving Faults","linkify":"Sending and Receiving Faults","nodes":[{"content":"Sending and Receiving Faults","pos":[0,28]}]},{"content":"SOAP faults convey error condition information from a service to a client and in the duplex case from a client to a service in an interoperable way.","pos":[241,389]},{"content":"Typically a service defines custom fault content and specifies which operations can return them.","pos":[390,486]},{"content":"(For more information, see <bpt id=\"p1\">[</bpt>Defining and Specifying Faults<ept id=\"p1\">](../../../docs/framework/wcf/defining-and-specifying-faults.md)</ept>.) This topic discusses how a service or duplex client can send those faults when the corresponding error condition has occurred and how a client or service application handles these faults.","pos":[487,799],"source":" (For more information, see [Defining and Specifying Faults](../../../docs/framework/wcf/defining-and-specifying-faults.md).) This topic discusses how a service or duplex client can send those faults when the corresponding error condition has occurred and how a client or service application handles these faults."},{"content":"For an overview of error handling in Windows Communication Foundation (WCF) applications, see <bpt id=\"p1\">[</bpt>Specifying and Handling Faults in Contracts and Services<ept id=\"p1\">](../../../docs/framework/wcf/specifying-and-handling-faults-in-contracts-and-services.md)</ept>.","pos":[800,1042],"source":" For an overview of error handling in Windows Communication Foundation (WCF) applications, see [Specifying and Handling Faults in Contracts and Services](../../../docs/framework/wcf/specifying-and-handling-faults-in-contracts-and-services.md)."},{"pos":[1051,1070],"content":"Sending SOAP Faults","linkify":"Sending SOAP Faults","nodes":[{"content":"Sending SOAP Faults","pos":[0,19]}]},{"content":"Declared SOAP faults are those in which an operation has a <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultContractAttribute?displayProperty=nameWithType&gt;</ph> that specifies a custom SOAP fault type.","pos":[1074,1252],"source":"Declared SOAP faults are those in which an operation has a <xref:System.ServiceModel.FaultContractAttribute?displayProperty=nameWithType> that specifies a custom SOAP fault type."},{"content":"Undeclared SOAP faults are those that are not specified in the contract for an operation.","pos":[1253,1342]},{"pos":[1352,1375],"content":"Sending Declared Faults","linkify":"Sending Declared Faults","nodes":[{"content":"Sending Declared Faults","pos":[0,23]}]},{"content":"To send a declared SOAP fault, detect the error condition for which the SOAP fault is appropriate and throw a new <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType&gt;</ph> where the type parameter is a new object of the type specified in the <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultContractAttribute&gt;</ph> for that operation.","pos":[1379,1707],"source":"To send a declared SOAP fault, detect the error condition for which the SOAP fault is appropriate and throw a new <xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType> where the type parameter is a new object of the type specified in the <xref:System.ServiceModel.FaultContractAttribute> for that operation."},{"content":"The following code example shows the use of <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultContractAttribute&gt;</ph> to specify that the <ph id=\"ph2\">`SampleMethod`</ph> operation can return a SOAP fault with the detail type of <ph id=\"ph3\">`GreetingFault`</ph>.","pos":[1708,1911],"source":" The following code example shows the use of <xref:System.ServiceModel.FaultContractAttribute> to specify that the `SampleMethod` operation can return a SOAP fault with the detail type of `GreetingFault`."},{"content":"To convey the <ph id=\"ph1\">`GreetingFault`</ph> error information to the client, catch the appropriate error condition and throw a new <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType&gt;</ph> of type <ph id=\"ph3\">`GreetingFault`</ph> with a new <ph id=\"ph4\">`GreetingFault`</ph> object as the argument, as in the following code example.","pos":[2188,2488],"source":"To convey the `GreetingFault` error information to the client, catch the appropriate error condition and throw a new <xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType> of type `GreetingFault` with a new `GreetingFault` object as the argument, as in the following code example."},{"content":"If the client is an WCF client application, it experiences this as a managed exception where the type is <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType&gt;</ph> of type <ph id=\"ph2\">`GreetingFault`</ph>.","pos":[2489,2693],"source":" If the client is an WCF client application, it experiences this as a managed exception where the type is <xref:System.ServiceModel.FaultException%601?displayProperty=nameWithType> of type `GreetingFault`."},{"pos":[2973,2998],"content":"Sending Undeclared Faults","linkify":"Sending Undeclared Faults","nodes":[{"content":"Sending Undeclared Faults","pos":[0,25]}]},{"content":"Sending undeclared faults can be very useful to quickly diagnose and debug problems in WCF applications, but its usefulness as a debugging tool is limited.","pos":[3002,3157]},{"content":"More generally, when debugging it is recommended that you use the <ph id=\"ph1\">&lt;xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> property.","pos":[3158,3356],"source":" More generally, when debugging it is recommended that you use the <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property."},{"content":"When you set this value to true, clients experience such faults as <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> exceptions of type <ph id=\"ph2\">&lt;xref:System.ServiceModel.ExceptionDetail&gt;</ph>.","pos":[3357,3532],"source":" When you set this value to true, clients experience such faults as <xref:System.ServiceModel.FaultException%601> exceptions of type <xref:System.ServiceModel.ExceptionDetail>."},{"pos":[3540,4042],"content":"[!IMPORTANT]\n Because managed exceptions can expose internal application information, setting <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> to `true` can permit WCF clients to obtain information about internal service operation exceptions, including personally identifiable or other sensitive information.","leadings":["","> "],"nodes":[{"content":"Because managed exceptions can expose internal application information, setting <ph id=\"ph1\">&lt;xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> or <ph id=\"ph2\">&lt;xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> to <ph id=\"ph3\">`true`</ph> can permit WCF clients to obtain information about internal service operation exceptions, including personally identifiable or other sensitive information.","pos":[14,500],"source":"Because managed exceptions can expose internal application information, setting <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> to `true` can permit WCF clients to obtain information about internal service operation exceptions, including personally identifiable or other sensitive information."}]},{"content":"Therefore, setting <ph id=\"ph1\">&lt;xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> or <ph id=\"ph2\">&lt;xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> to <ph id=\"ph3\">`true`</ph> is only recommended as a way of temporarily debugging a service application.","pos":[4053,4399],"source":"Therefore, setting <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> to `true` is only recommended as a way of temporarily debugging a service application."},{"content":"In addition, the WSDL for a method that returns unhandled managed exceptions in this way does not contain the contract for the <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> of type <ph id=\"ph2\">&lt;xref:System.ServiceModel.ExceptionDetail&gt;</ph>.","pos":[4400,4624],"source":" In addition, the WSDL for a method that returns unhandled managed exceptions in this way does not contain the contract for the <xref:System.ServiceModel.FaultException%601> of type <xref:System.ServiceModel.ExceptionDetail>."},{"content":"Clients must expect the possibility of an unknown SOAP fault (returned to WCF clients as <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException?displayProperty=nameWithType&gt;</ph> objects) to obtain the debugging information properly.","pos":[4625,4839],"source":" Clients must expect the possibility of an unknown SOAP fault (returned to WCF clients as <xref:System.ServiceModel.FaultException?displayProperty=nameWithType> objects) to obtain the debugging information properly."},{"content":"To send an undeclared SOAP fault, throw a <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException?displayProperty=nameWithType&gt;</ph> object (that is, not the generic type <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph>) and pass the string to the constructor.","pos":[4846,5083],"source":"To send an undeclared SOAP fault, throw a <xref:System.ServiceModel.FaultException?displayProperty=nameWithType> object (that is, not the generic type <xref:System.ServiceModel.FaultException%601>) and pass the string to the constructor."},{"content":"This is exposed to the WCF client applications as a thrown <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException?displayProperty=nameWithType&gt;</ph> exception where the string is available by calling the <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType&gt;</ph> method.","pos":[5084,5363],"source":" This is exposed to the WCF client applications as a thrown <xref:System.ServiceModel.FaultException?displayProperty=nameWithType> exception where the string is available by calling the <xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType> method."},{"pos":[5371,5837],"content":"[!NOTE]\n If you declare a SOAP fault of type string, and then throw this in your service as a <xref:System.ServiceModel.FaultException%601> where the type parameter is a <xref:System.String?displayProperty=nameWithType> the string value is assigned to the <xref:System.ServiceModel.FaultException%601.Detail%2A?displayProperty=nameWithType> property, and is not available from <xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType>.","leadings":["","> "],"nodes":[{"content":"If you declare a SOAP fault of type string, and then throw this in your service as a <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> where the type parameter is a <ph id=\"ph2\">&lt;xref:System.String?displayProperty=nameWithType&gt;</ph> the string value is assigned to the <ph id=\"ph3\">&lt;xref:System.ServiceModel.FaultException%601.Detail%2A?displayProperty=nameWithType&gt;</ph> property, and is not available from <ph id=\"ph4\">&lt;xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType&gt;</ph>.","pos":[9,464],"source":"If you declare a SOAP fault of type string, and then throw this in your service as a <xref:System.ServiceModel.FaultException%601> where the type parameter is a <xref:System.String?displayProperty=nameWithType> the string value is assigned to the <xref:System.ServiceModel.FaultException%601.Detail%2A?displayProperty=nameWithType> property, and is not available from <xref:System.ServiceModel.FaultException%601.ToString%2A?displayProperty=nameWithType>."}]},{"pos":[5846,5861],"content":"Handling Faults","linkify":"Handling Faults","nodes":[{"content":"Handling Faults","pos":[0,15]}]},{"content":"In WCF clients, SOAP faults that occur during communication that are of interest to client applications are raised as managed exceptions.","pos":[5865,6002]},{"content":"While there are many exceptions that can occur during the execution of any program, applications using the WCF client programming model can expect to handle exceptions of the following two types as a result of communication.","pos":[6003,6227]},{"pos":[6333,6438],"content":"<ph id=\"ph1\">&lt;xref:System.TimeoutException&gt;</ph> objects are thrown when an operation exceeds the specified timeout period.","source":"<xref:System.TimeoutException> objects are thrown when an operation exceeds the specified timeout period."},{"pos":[6445,6611],"content":"<ph id=\"ph1\">&lt;xref:System.ServiceModel.CommunicationException&gt;</ph> objects are thrown when there is some recoverable communication error condition on either the service or the client.","source":"<xref:System.ServiceModel.CommunicationException> objects are thrown when there is some recoverable communication error condition on either the service or the client."},{"pos":[6618,6820],"content":"The <ph id=\"ph1\">&lt;xref:System.ServiceModel.CommunicationException&gt;</ph> class has two important derived types, <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultException&gt;</ph> and the generic <ph id=\"ph3\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> type.","source":"The <xref:System.ServiceModel.CommunicationException> class has two important derived types, <xref:System.ServiceModel.FaultException> and the generic <xref:System.ServiceModel.FaultException%601> type."},{"pos":[6827,7214],"content":"<ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException&gt;</ph> exceptions are thrown when a listener receives a fault that is not expected or specified in the operation contract; usually this occurs when the application is being debugged and the service has the <ph id=\"ph2\">&lt;xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> property set to <ph id=\"ph3\">`true`</ph>.","source":"<xref:System.ServiceModel.FaultException> exceptions are thrown when a listener receives a fault that is not expected or specified in the operation contract; usually this occurs when the application is being debugged and the service has the <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property set to `true`."},{"pos":[7221,7585],"content":"<ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> exceptions are thrown on the client when a fault that is specified in the operation contract is received in response to a two-way operation (that is, a method with an <ph id=\"ph2\">&lt;xref:System.ServiceModel.OperationContractAttribute&gt;</ph> attribute with <ph id=\"ph3\">&lt;xref:System.ServiceModel.OperationContractAttribute.IsOneWay%2A&gt;</ph> set to <ph id=\"ph4\">`false`</ph>).","source":"<xref:System.ServiceModel.FaultException%601> exceptions are thrown on the client when a fault that is specified in the operation contract is received in response to a two-way operation (that is, a method with an <xref:System.ServiceModel.OperationContractAttribute> attribute with <xref:System.ServiceModel.OperationContractAttribute.IsOneWay%2A> set to `false`)."},{"pos":[7593,8167],"content":"[!NOTE]\n When an WCF service has the <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property set to `true` the client experiences this as an undeclared <xref:System.ServiceModel.FaultException%601> of type <xref:System.ServiceModel.ExceptionDetail>. Clients can either catch this specific fault or handle the fault in a catch block for <xref:System.ServiceModel.FaultException>.","leadings":["","> "],"nodes":[{"content":"When an WCF service has the <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property set to `true` the client experiences this as an undeclared <xref:System.ServiceModel.FaultException%601> of type <xref:System.ServiceModel.ExceptionDetail>. Clients can either catch this specific fault or handle the fault in a catch block for <xref:System.ServiceModel.FaultException>.","pos":[9,572],"nodes":[{"content":"When an WCF service has the <ph id=\"ph1\">&lt;xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> or <ph id=\"ph2\">&lt;xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType&gt;</ph> property set to <ph id=\"ph3\">`true`</ph> the client experiences this as an undeclared <ph id=\"ph4\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> of type <ph id=\"ph5\">&lt;xref:System.ServiceModel.ExceptionDetail&gt;</ph>.","pos":[0,434],"source":"When an WCF service has the <xref:System.ServiceModel.ServiceBehaviorAttribute.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> or <xref:System.ServiceModel.Description.ServiceDebugBehavior.IncludeExceptionDetailInFaults%2A?displayProperty=nameWithType> property set to `true` the client experiences this as an undeclared <xref:System.ServiceModel.FaultException%601> of type <xref:System.ServiceModel.ExceptionDetail>."},{"content":"Clients can either catch this specific fault or handle the fault in a catch block for <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException&gt;</ph>.","pos":[435,563],"source":" Clients can either catch this specific fault or handle the fault in a catch block for <xref:System.ServiceModel.FaultException>."}]}]},{"pos":[8174,8374],"content":"Typically, only <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph>, <ph id=\"ph2\">&lt;xref:System.TimeoutException&gt;</ph>, and <ph id=\"ph3\">&lt;xref:System.ServiceModel.CommunicationException&gt;</ph> exceptions are of interest to clients and services.","source":"Typically, only <xref:System.ServiceModel.FaultException%601>, <xref:System.TimeoutException>, and <xref:System.ServiceModel.CommunicationException> exceptions are of interest to clients and services."},{"pos":[8382,8607],"content":"[!NOTE]\n Other exceptions, of course, do occur. Unexpected exceptions include catastrophic failures like <xref:System.OutOfMemoryException?displayProperty=nameWithType>; typically applications should not catch such methods.","leadings":["","> "],"nodes":[{"content":"Other exceptions, of course, do occur. Unexpected exceptions include catastrophic failures like <xref:System.OutOfMemoryException?displayProperty=nameWithType>; typically applications should not catch such methods.","pos":[9,223],"nodes":[{"content":"Other exceptions, of course, do occur.","pos":[0,38]},{"content":"Unexpected exceptions include catastrophic failures like <ph id=\"ph1\">&lt;xref:System.OutOfMemoryException?displayProperty=nameWithType&gt;</ph>; typically applications should not catch such methods.","pos":[39,214],"source":" Unexpected exceptions include catastrophic failures like <xref:System.OutOfMemoryException?displayProperty=nameWithType>; typically applications should not catch such methods."}]}]},{"pos":[8617,8660],"content":"Catch Fault Exceptions in the Correct Order","linkify":"Catch Fault Exceptions in the Correct Order","nodes":[{"content":"Catch Fault Exceptions in the Correct Order","pos":[0,43]}]},{"content":"Because <ph id=\"ph1\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> derives from <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultException&gt;</ph>, and <ph id=\"ph3\">&lt;xref:System.ServiceModel.FaultException&gt;</ph> derives from <ph id=\"ph4\">&lt;xref:System.ServiceModel.CommunicationException&gt;</ph>, it is important to catch these exceptions in the proper order.","pos":[8664,8946],"source":"Because <xref:System.ServiceModel.FaultException%601> derives from <xref:System.ServiceModel.FaultException>, and <xref:System.ServiceModel.FaultException> derives from <xref:System.ServiceModel.CommunicationException>, it is important to catch these exceptions in the proper order."},{"content":"If, for example, you have a try/catch block in which you first catch <ph id=\"ph1\">&lt;xref:System.ServiceModel.CommunicationException&gt;</ph>, all specified and unspecified SOAP faults are handled there; any subsequent catch blocks to handle a custom <ph id=\"ph2\">&lt;xref:System.ServiceModel.FaultException%601&gt;</ph> exception are never invoked.","pos":[8947,9249],"source":" If, for example, you have a try/catch block in which you first catch <xref:System.ServiceModel.CommunicationException>, all specified and unspecified SOAP faults are handled there; any subsequent catch blocks to handle a custom <xref:System.ServiceModel.FaultException%601> exception are never invoked."},{"content":"Remember that one operation can return any number of specified faults.","pos":[9256,9326]},{"content":"Each fault is a unique type and must be handled separately.","pos":[9327,9386]},{"pos":[9396,9438],"content":"Handle Exceptions When Closing the Channel","linkify":"Handle Exceptions When Closing the Channel","nodes":[{"content":"Handle Exceptions When Closing the Channel","pos":[0,42]}]},{"content":"Most of the preceding discussion has to do with faults sent in the course of processing application messages, that is, messages explicitly sent by the client when the client application calls operations on the WCF client object.","pos":[9442,9670]},{"content":"Even with local objects disposing the object can either raise or mask exceptions that occur during the recycling process.","pos":[9677,9798]},{"content":"Something similar can occur when you use WCF client objects.","pos":[9799,9859]},{"content":"When you call operations you are sending messages over an established connection.","pos":[9860,9941]},{"content":"Closing the channel can throw exceptions if the connection cannot be cleanly closed or is already closed, even if all the operations returned properly.","pos":[9942,10093]},{"content":"Typically, client object channels are closed in one of the following ways:","pos":[10100,10174]},{"content":"When the WCF client object is recycled.","pos":[10184,10223]},{"pos":[10233,10347],"content":"When the client application calls <ph id=\"ph1\">&lt;xref:System.ServiceModel.ClientBase%601.Close%2A?displayProperty=nameWithType&gt;</ph>.","source":"When the client application calls <xref:System.ServiceModel.ClientBase%601.Close%2A?displayProperty=nameWithType>."},{"pos":[10357,10477],"content":"When the client application calls <ph id=\"ph1\">&lt;xref:System.ServiceModel.ICommunicationObject.Close%2A?displayProperty=nameWithType&gt;</ph>.","source":"When the client application calls <xref:System.ServiceModel.ICommunicationObject.Close%2A?displayProperty=nameWithType>."},{"content":"When the client application calls an operation that is a terminating operation for a session.","pos":[10487,10580]},{"content":"In all cases, closing the channel instructs the channel to begin closing any underlying channels that may be sending messages to support complex functionality at the application level.","pos":[10587,10771]},{"content":"For example, when a contract requires sessions a binding attempts to establish a session by exchanging messages with the service channel until a session is established.","pos":[10772,10940]},{"content":"When the channel is closed, the underlying session channel notifies the service that the session is terminated.","pos":[10941,11052]},{"content":"In this case, if the channel has already aborted, closed, or is otherwise unusable (for example, when a network cable is unplugged), the client channel cannot inform the service channel that the session is terminated and an exception can result.","pos":[11053,11298]},{"pos":[11308,11338],"content":"Abort the Channel If Necessary","linkify":"Abort the Channel If Necessary","nodes":[{"content":"Abort the Channel If Necessary","pos":[0,30]}]},{"content":"Because closing the channel can also throw exceptions, then, it is recommended that in addition to catching fault exceptions in the correct order, it is important to abort the channel that was used in making the call in the catch block.","pos":[11342,11578]},{"content":"If the fault conveys error information specific to an operation and it remains possible that others can use it, there is no need to abort the channel (although these cases are rare).","pos":[11585,11767]},{"content":"In all other cases, it is recommended that you abort the channel.","pos":[11768,11833]},{"content":"For a sample that demonstrates all of these points, see <bpt id=\"p1\">[</bpt>Expected Exceptions<ept id=\"p1\">](../../../docs/framework/wcf/samples/expected-exceptions.md)</ept>.","pos":[11834,11972],"source":" For a sample that demonstrates all of these points, see [Expected Exceptions](../../../docs/framework/wcf/samples/expected-exceptions.md)."},{"content":"The following code example shows how to handle SOAP fault exceptions in a basic client application, including a declared fault and an undeclared fault.","pos":[11979,12130]},{"pos":[12138,12614],"content":"[!NOTE]\n This sample code does not use the `using` construct. Because closing channels can throw exceptions, it is recommended that applications create a WCF client first, and then open, use, and close the WCF client in the same try block. For details, see [WCF Client Overview](../../../docs/framework/wcf/wcf-client-overview.md) and [Use Close and Abort to release WCF client resources](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md).","leadings":["","> "],"nodes":[{"content":"This sample code does not use the `using` construct. Because closing channels can throw exceptions, it is recommended that applications create a WCF client first, and then open, use, and close the WCF client in the same try block. For details, see [WCF Client Overview](../../../docs/framework/wcf/wcf-client-overview.md) and [Use Close and Abort to release WCF client resources](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md).","pos":[9,474],"nodes":[{"content":"This sample code does not use the <ph id=\"ph1\">`using`</ph> construct.","pos":[0,52],"source":"This sample code does not use the `using` construct."},{"content":"Because closing channels can throw exceptions, it is recommended that applications create a WCF client first, and then open, use, and close the WCF client in the same try block.","pos":[53,230]},{"content":"For details, see <bpt id=\"p1\">[</bpt>WCF Client Overview<ept id=\"p1\">](../../../docs/framework/wcf/wcf-client-overview.md)</ept> and <bpt id=\"p2\">[</bpt>Use Close and Abort to release WCF client resources<ept id=\"p2\">](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md)</ept>.","pos":[231,465],"source":" For details, see [WCF Client Overview](../../../docs/framework/wcf/wcf-client-overview.md) and [Use Close and Abort to release WCF client resources](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md)."}]}]},{"pos":[12889,12897],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[13074,13155],"content":"<bpt id=\"p1\">[</bpt>Expected Exceptions<ept id=\"p1\">](../../../docs/framework/wcf/samples/expected-exceptions.md)</ept>","source":"[Expected Exceptions](../../../docs/framework/wcf/samples/expected-exceptions.md)"},{"pos":[13158,13296],"content":"<bpt id=\"p1\">[</bpt>Use Close and Abort to release WCF client resources<ept id=\"p1\">](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md)</ept>","source":"[Use Close and Abort to release WCF client resources](../../../docs/framework/wcf/samples/use-close-abort-release-wcf-client-resources.md)"}]}