{"content":"---\ntitle: \"1004 - WorkflowInstanceAborted | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net-framework\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nms.assetid: edb9ab8c-0b9a-488d-aa96-9c8c7984b53c\ncaps.latest.revision: 4\nauthor: \"Erikre\"\nms.author: \"erikre\"\nmanager: \"erikre\"\n---\n# 1004 - WorkflowInstanceAborted\n## Properties  \n  \n|||  \n|-|-|  \n|ID|1004|  \n|Keywords|WFRuntime|  \n|Level|Information|  \n|Channel|Microsoft-Windows-Application Server-Applications/Debug|  \n  \n## Description  \n Indicates a worfklow instance has aborted with an exception.  \n  \n## Message  \n WorkflowInstance Id: '%1' was aborted with an exception.  \n  \n## Details  \n  \n|Data Item Name|Data Item Type|Description|  \n|--------------------|--------------------|-----------------|  \n|WorkflowInstanceId|`xs:string`|The instance id for the workflow|  \n|Exception|`xs:string`|The exception details for the exception|  \n|AppDomain|`xs:string`|The string returned by AppDomain.CurrentDomain.FriendlyName.|","nodes":[{"pos":[12,59],"content":"1004 - WorkflowInstanceAborted | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"1004 - WorkflowInstanceAborted | Microsoft Docs","pos":[0,47]}]},{"pos":[324,354],"content":"1004 - WorkflowInstanceAborted","linkify":"1004 - WorkflowInstanceAborted","nodes":[{"content":"1004 - WorkflowInstanceAborted","pos":[0,30]}]},{"pos":[358,368],"content":"Properties","linkify":"Properties","nodes":[{"content":"Properties","pos":[0,10]}]},{"content":"ID","pos":[389,391]},{"content":"1004","pos":[392,396]},{"content":"Keywords","pos":[401,409]},{"content":"WFRuntime","pos":[410,419]},{"content":"Level","pos":[424,429]},{"content":"Information","pos":[430,441]},{"content":"Channel","pos":[446,453]},{"content":"Microsoft-Windows-Application Server-Applications/Debug","pos":[454,509]},{"pos":[519,530],"content":"Description","linkify":"Description","nodes":[{"content":"Description","pos":[0,11]}]},{"content":"Indicates a worfklow instance has aborted with an exception.","pos":[534,594]},{"pos":[603,610],"content":"Message","linkify":"Message","nodes":[{"content":"Message","pos":[0,7]}]},{"content":"WorkflowInstance Id: '%1' was aborted with an exception.","pos":[614,670]},{"pos":[679,686],"content":"Details","linkify":"Details","nodes":[{"content":"Details","pos":[0,7]}]},{"content":"Data Item Name","pos":[693,707]},{"content":"Data Item Type","pos":[708,722]},{"content":"Description","pos":[723,734]},{"content":"WorkflowInstanceId","pos":[803,821]},{"content":"The instance id for the workflow","pos":[834,866]},{"content":"Exception","pos":[871,880]},{"content":"The exception details for the exception","pos":[893,932]},{"content":"AppDomain","pos":[937,946]},{"content":"The string returned by AppDomain.CurrentDomain.FriendlyName.","pos":[959,1019]}]}