{"content":"---\ntitle: \"Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"vbc30616\"\n  - \"bc30616\"\ndev_langs: \n  - \"VB\"\nhelpviewer_keywords: \n  - \"BC30616\"\nms.assetid: e7658ebc-da45-451b-a409-a0f8915f0beb\ncaps.latest.revision: 8\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block\nA variable enclosed in a block has the same name as another local variable.  \n  \n **Error ID:** BC30616  \n  \n## To correct this error  \n  \n-   Rename the variable in the enclosed block so that it is not the same as any other local variables. For example:  \n  \n    ```  \n    Dim a, b, x As Integer  \n    If a = b Then  \n       Dim y As Integer = 20 ' Uniquely named block variable.  \n    End If  \n    ```  \n  \n-   A common cause for this error is the use of `Catch e As Exception` inside an event handler. If this is the case, name the `Catch` block variable `ex` rather than `e`.  \n  \n-   Another common source of this error is an attempt to access a local variable declared within a `Try` block in a separate `Catch` block. To correct this, declare the variable outside the `Try...Catch...Finally` structure.  \n  \n## See Also  \n [Try...Catch...Finally Statement](../../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   \n [Variable Declaration](../../../visual-basic/programming-guide/language-features/variables/variable-declaration.md)","nodes":[{"pos":[12,107],"content":"Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"Variable &amp;#39;<ph id=\"ph1\">&amp;lt;</ph>variablename<ph id=\"ph2\">&amp;gt;</ph>&amp;#39; hides a variable in an enclosing block | Microsoft Docs","pos":[0,95],"source":"Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block | Microsoft Docs"}]},{"pos":[645,723],"content":"Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block","linkify":"Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block","nodes":[{"content":"Variable &amp;#39;<ph id=\"ph1\">&amp;lt;</ph>variablename<ph id=\"ph2\">&amp;gt;</ph>&amp;#39; hides a variable in an enclosing block","pos":[0,78],"source":"Variable &#39;&lt;variablename&gt;&#39; hides a variable in an enclosing block"}]},{"content":"A variable enclosed in a block has the same name as another local variable.","pos":[724,799]},{"pos":[806,827],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30616","source":"**Error ID:** BC30616"},{"pos":[836,857],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"content":"Rename the variable in the enclosed block so that it is not the same as any other local variables.","pos":[867,965]},{"content":"For example:","pos":[966,978]},{"content":"A common cause for this error is the use of <ph id=\"ph1\">`Catch e As Exception`</ph> inside an event handler.","pos":[1137,1228],"source":"A common cause for this error is the use of `Catch e As Exception` inside an event handler."},{"content":"If this is the case, name the <ph id=\"ph1\">`Catch`</ph> block variable <ph id=\"ph2\">`ex`</ph> rather than <ph id=\"ph3\">`e`</ph>.","pos":[1229,1303],"source":" If this is the case, name the `Catch` block variable `ex` rather than `e`."},{"content":"Another common source of this error is an attempt to access a local variable declared within a <ph id=\"ph1\">`Try`</ph> block in a separate <ph id=\"ph2\">`Catch`</ph> block.","pos":[1313,1448],"source":"Another common source of this error is an attempt to access a local variable declared within a `Try` block in a separate `Catch` block."},{"content":"To correct this, declare the variable outside the <ph id=\"ph1\">`Try...Catch...Finally`</ph> structure.","pos":[1449,1533],"source":" To correct this, declare the variable outside the `Try...Catch...Finally` structure."},{"pos":[1542,1550],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept><ph id=\"ph1\"> </ph>","pos":[1554,1672],"source":"[Try...Catch...Finally Statement](../../../visual-basic/language-reference/statements/try-catch-finally-statement.md) "},{"content":"<bpt id=\"p1\"> [</bpt>Variable Declaration<ept id=\"p1\">](../../../visual-basic/programming-guide/language-features/variables/variable-declaration.md)</ept>","pos":[1675,1791],"source":" [Variable Declaration](../../../visual-basic/programming-guide/language-features/variables/variable-declaration.md)"}]}