{"content":"---\ntitle: \"1126 - InvokedMethodThrewException | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net-framework\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nms.assetid: 0d3cff1a-97e6-4b6c-be18-108c6881bfc0\ncaps.latest.revision: 2\nauthor: \"Erikre\"\nms.author: \"erikre\"\nmanager: \"erikre\"\n---\n# 1126 - InvokedMethodThrewException\n## Properties  \n  \n|||  \n|-|-|  \n|ID|1126|  \n|Keywords|WFRuntime|  \n|Level|Information|  \n|Channel|Microsoft-Windows-Application Server-Applications/Debug|  \n  \n## Description  \n Indicates an exception was thrown by the method called by the InvokeMethod activity.  \n  \n## Message  \n An exception was thrown in the method called by the activity '%1'. %2  \n  \n## Details  \n  \n|Data Item Name|Data Item Type|Description|  \n|--------------------|--------------------|-----------------|  \n|InvokeMethod|xs:string|The display name of the InvokeMethod activity.|  \n|Exception|xs:string|The exception details for the exception|  \n|AppDomain|xs:string|The string returned by AppDomain.CurrentDomain.FriendlyName.|","nodes":[{"pos":[12,63],"content":"1126 - InvokedMethodThrewException | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"1126 - InvokedMethodThrewException | Microsoft Docs","pos":[0,51]}]},{"pos":[328,362],"content":"1126 - InvokedMethodThrewException","linkify":"1126 - InvokedMethodThrewException","nodes":[{"content":"1126 - InvokedMethodThrewException","pos":[0,34]}]},{"pos":[366,376],"content":"Properties","linkify":"Properties","nodes":[{"content":"Properties","pos":[0,10]}]},{"content":"ID","pos":[397,399]},{"content":"1126","pos":[400,404]},{"content":"Keywords","pos":[409,417]},{"content":"WFRuntime","pos":[418,427]},{"content":"Level","pos":[432,437]},{"content":"Information","pos":[438,449]},{"content":"Channel","pos":[454,461]},{"content":"Microsoft-Windows-Application Server-Applications/Debug","pos":[462,517]},{"pos":[527,538],"content":"Description","linkify":"Description","nodes":[{"content":"Description","pos":[0,11]}]},{"content":"Indicates an exception was thrown by the method called by the InvokeMethod activity.","pos":[542,626]},{"pos":[635,642],"content":"Message","linkify":"Message","nodes":[{"content":"Message","pos":[0,7]}]},{"content":"An exception was thrown in the method called by the activity '%1'.","pos":[646,712]},{"content":"%2","pos":[713,715]},{"pos":[724,731],"content":"Details","linkify":"Details","nodes":[{"content":"Details","pos":[0,7]}]},{"content":"Data Item Name","pos":[738,752]},{"content":"Data Item Type","pos":[753,767]},{"content":"Description","pos":[768,779]},{"content":"InvokeMethod","pos":[848,860]},{"content":"xs:string","pos":[861,870]},{"content":"The display name of the InvokeMethod activity.","pos":[871,917]},{"content":"Exception","pos":[922,931]},{"content":"xs:string","pos":[932,941]},{"content":"The exception details for the exception","pos":[942,981]},{"content":"AppDomain","pos":[986,995]},{"content":"xs:string","pos":[996,1005]},{"content":"The string returned by AppDomain.CurrentDomain.FriendlyName.","pos":[1006,1066]}]}