{"content":"---\ntitle: \"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"vbc30666\"\n  - \"bc30666\"\nhelpviewer_keywords: \n  - \"BC30666\"\nms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a\n---\n# 'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement\n`Throw` statements outside of `Catch` statement must supply the name of an exception object.  \n  \n **Error ID:** BC30666  \n  \n## To correct this error  \n  \n1.  Specify the name of an exception object derived from `System.Exception`.  \n  \n2.  Restructure your code so that the `Throw` statement is inside a `Catch` block.  \n  \n## See also\n\n- [Throw Statement](../../visual-basic/language-reference/statements/throw-statement.md)\n- [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)\n- <xref:System.Exception?displayProperty=nameWithType>\n- [Handling and throwing exceptions in .NET](../../standard/exceptions/index.md)\n","nodes":[{"pos":[4,258],"embed":true,"restype":"x-metadata","content":"title: \"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"vbc30666\"\n  - \"bc30666\"\nhelpviewer_keywords: \n  - \"BC30666\"\nms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a","nodes":[{"content":"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement","nodes":[{"pos":[0,97],"content":"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement","nodes":[{"content":"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement","pos":[0,97]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[265,362],"content":"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement","linkify":"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement","nodes":[{"content":"'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement","pos":[0,97]}]},{"pos":[363,455],"content":"<ph id=\"ph1\">`Throw`</ph> statements outside of <ph id=\"ph2\">`Catch`</ph> statement must supply the name of an exception object.","source":"`Throw` statements outside of `Catch` statement must supply the name of an exception object."},{"pos":[462,483],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30666","source":"**Error ID:** BC30666"},{"pos":[492,513],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[523,595],"content":"Specify the name of an exception object derived from <ph id=\"ph1\">`System.Exception`</ph>.","source":"Specify the name of an exception object derived from `System.Exception`."},{"pos":[605,683],"content":"Restructure your code so that the <ph id=\"ph1\">`Throw`</ph> statement is inside a <ph id=\"ph2\">`Catch`</ph> block.","source":"Restructure your code so that the `Throw` statement is inside a `Catch` block."},{"pos":[692,700],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[704,790],"content":"<bpt id=\"p1\">[</bpt>Throw Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/throw-statement.md)</ept>","source":"[Throw Statement](../../visual-basic/language-reference/statements/throw-statement.md)"},{"pos":[793,907],"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept>","source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)"},{"pos":[965,1043],"content":"<bpt id=\"p1\">[</bpt>Handling and throwing exceptions in .NET<ept id=\"p1\">](../../standard/exceptions/index.md)</ept>","source":"[Handling and throwing exceptions in .NET](../../standard/exceptions/index.md)"}]}