{"content":"# [Exceptions and Exception Handling](index.md)\n## [Using Exceptions](using-exceptions.md)\n## [Exception Handling](exception-handling.md)\n## [Creating and Throwing Exceptions](creating-and-throwing-exceptions.md)\n## [Compiler-Generated Exceptions](compiler-generated-exceptions.md)\n## [How to: Handle an Exception Using try-catch](how-to-handle-an-exception-using-try-catch.md)\n## [How to: Execute Cleanup Code Using finally](how-to-execute-cleanup-code-using-finally.md)\n## [How to: Catch a non-CLS Exception](how-to-catch-a-non-cls-exception.md)\n","nodes":[{"pos":[2,47],"content":"<bpt id=\"p1\">[</bpt>Exceptions and Exception Handling<ept id=\"p1\">](index.md)</ept>","linkify":"[Exceptions and Exception Handling](index.md)","source":"[Exceptions and Exception Handling](index.md)"},{"pos":[51,90],"content":"<bpt id=\"p1\">[</bpt>Using Exceptions<ept id=\"p1\">](using-exceptions.md)</ept>","linkify":"[Using Exceptions](using-exceptions.md)","source":"[Using Exceptions](using-exceptions.md)"},{"pos":[94,137],"content":"<bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](exception-handling.md)</ept>","linkify":"[Exception Handling](exception-handling.md)","source":"[Exception Handling](exception-handling.md)"},{"pos":[141,212],"content":"<bpt id=\"p1\">[</bpt>Creating and Throwing Exceptions<ept id=\"p1\">](creating-and-throwing-exceptions.md)</ept>","linkify":"[Creating and Throwing Exceptions](creating-and-throwing-exceptions.md)","source":"[Creating and Throwing Exceptions](creating-and-throwing-exceptions.md)"},{"pos":[216,281],"content":"<bpt id=\"p1\">[</bpt>Compiler-Generated Exceptions<ept id=\"p1\">](compiler-generated-exceptions.md)</ept>","linkify":"[Compiler-Generated Exceptions](compiler-generated-exceptions.md)","source":"[Compiler-Generated Exceptions](compiler-generated-exceptions.md)"},{"pos":[285,377],"content":"<bpt id=\"p1\">[</bpt>How to: Handle an Exception Using try-catch<ept id=\"p1\">](how-to-handle-an-exception-using-try-catch.md)</ept>","linkify":"[How to: Handle an Exception Using try-catch](how-to-handle-an-exception-using-try-catch.md)","source":"[How to: Handle an Exception Using try-catch](how-to-handle-an-exception-using-try-catch.md)"},{"pos":[381,471],"content":"<bpt id=\"p1\">[</bpt>How to: Execute Cleanup Code Using finally<ept id=\"p1\">](how-to-execute-cleanup-code-using-finally.md)</ept>","linkify":"[How to: Execute Cleanup Code Using finally](how-to-execute-cleanup-code-using-finally.md)","source":"[How to: Execute Cleanup Code Using finally](how-to-execute-cleanup-code-using-finally.md)"},{"pos":[475,547],"content":"<bpt id=\"p1\">[</bpt>How to: Catch a non-CLS Exception<ept id=\"p1\">](how-to-catch-a-non-cls-exception.md)</ept>","linkify":"[How to: Catch a non-CLS Exception](how-to-catch-a-non-cls-exception.md)","source":"[How to: Catch a non-CLS Exception](how-to-catch-a-non-cls-exception.md)"}]}