{"content":"---\ntitle: \"57395 - ShipAssertExceptionMessage | Microsoft Docs\"\nms.custom: \"\"\nms.date: \"03/30/2017\"\nms.prod: \".net-framework\"\nms.reviewer: \"\"\nms.suite: \"\"\nms.technology: \n  - \"dotnet-clr\"\nms.tgt_pltfrm: \"\"\nms.topic: \"article\"\nms.assetid: 37f0c15b-e34e-42fe-8f86-b122e592add5\ncaps.latest.revision: 3\nauthor: \"Erikre\"\nms.author: \"erikre\"\nmanager: \"erikre\"\n---\n# 57395 - ShipAssertExceptionMessage\n## Properties  \n  \n|||  \n|-|-|  \n|ID|57395|  \n|Keywords|Infrastructure|  \n|Level|Error|  \n|Channel|Microsoft-Windows-Application Server-Applications/Analytic|  \n  \n## Description  \n This event is emitted when an unexpected failure occurred.  \n  \n## Message  \n An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: %1.  \n  \n## Details","nodes":[{"pos":[12,63],"content":"57395 - ShipAssertExceptionMessage | Microsoft Docs","needQuote":false,"needEscape":true,"nodes":[{"content":"57395 - ShipAssertExceptionMessage | Microsoft Docs","pos":[0,51]}]},{"pos":[361,395],"content":"57395 - ShipAssertExceptionMessage","linkify":"57395 - ShipAssertExceptionMessage","nodes":[{"content":"57395 - ShipAssertExceptionMessage","pos":[0,34]}]},{"pos":[399,409],"content":"Properties","linkify":"Properties","nodes":[{"content":"Properties","pos":[0,10]}]},{"content":"ID","pos":[430,432]},{"content":"57395","pos":[433,438]},{"content":"Keywords","pos":[443,451]},{"content":"Infrastructure","pos":[452,466]},{"content":"Level","pos":[471,476]},{"content":"Error","pos":[477,482]},{"content":"Channel","pos":[487,494]},{"content":"Microsoft-Windows-Application Server-Applications/Analytic","pos":[495,553]},{"pos":[563,574],"content":"Description","linkify":"Description","nodes":[{"content":"Description","pos":[0,11]}]},{"content":"This event is emitted when an unexpected failure occurred.","pos":[578,636]},{"pos":[645,652],"content":"Message","linkify":"Message","nodes":[{"content":"Message","pos":[0,7]}]},{"content":"An unexpected failure occurred.","pos":[656,687]},{"content":"Applications should not attempt to handle this error.","pos":[688,741]},{"content":"For diagnostic purposes, this English message is associated with the failure: %1.","pos":[742,823]},{"pos":[832,839],"content":"Details","linkify":"Details","nodes":[{"content":"Details","pos":[0,7]}]}]}