{"content":"---\ntitle: \"'Catch' cannot appear outside a 'Try' statement\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"bc30380\"\n  - \"vbc30380\"\nhelpviewer_keywords: \n  - \"BC30380\"\nms.assetid: 73ce950d-881f-4532-8024-40a4930abd32\n---\n# 'Catch' cannot appear outside a 'Try' statement\n`Catch` must appear within a `Try...Catch...Finally` statement block. Either you have an unnecessary `Catch` statement in your `Try` block, or your `Catch` statement appears outside the bounds of its corresponding `Try` block.  \n  \n **Error ID:** BC30380  \n  \n## To correct this error  \n  \n1.  Delete the `Catch` statement if it is unnecessary, or place it within a `Try...Catch...Finally` statement block.  \n  \n## See also\n\n- [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)\n","nodes":[{"pos":[4,208],"embed":true,"restype":"x-metadata","content":"title: \"'Catch' cannot appear outside a 'Try' statement\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"bc30380\"\n  - \"vbc30380\"\nhelpviewer_keywords: \n  - \"BC30380\"\nms.assetid: 73ce950d-881f-4532-8024-40a4930abd32","nodes":[{"content":"'Catch' cannot appear outside a 'Try' statement","nodes":[{"pos":[0,47],"content":"'Catch' cannot appear outside a 'Try' statement","nodes":[{"content":"'Catch' cannot appear outside a 'Try' statement","pos":[0,47]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[215,262],"content":"'Catch' cannot appear outside a 'Try' statement","linkify":"'Catch' cannot appear outside a 'Try' statement","nodes":[{"content":"'Catch' cannot appear outside a 'Try' statement","pos":[0,47]}]},{"content":"<ph id=\"ph1\">`Catch`</ph> must appear within a <ph id=\"ph2\">`Try...Catch...Finally`</ph> statement block.","pos":[263,332],"source":"`Catch` must appear within a `Try...Catch...Finally` statement block."},{"content":"Either you have an unnecessary <ph id=\"ph1\">`Catch`</ph> statement in your <ph id=\"ph2\">`Try`</ph> block, or your <ph id=\"ph3\">`Catch`</ph> statement appears outside the bounds of its corresponding <ph id=\"ph4\">`Try`</ph> block.","pos":[333,489],"source":" Either you have an unnecessary `Catch` statement in your `Try` block, or your `Catch` statement appears outside the bounds of its corresponding `Try` block."},{"pos":[496,517],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30380","source":"**Error ID:** BC30380"},{"pos":[526,547],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[557,669],"content":"Delete the <ph id=\"ph1\">`Catch`</ph> statement if it is unnecessary, or place it within a <ph id=\"ph2\">`Try...Catch...Finally`</ph> statement block.","source":"Delete the `Catch` statement if it is unnecessary, or place it within a `Try...Catch...Finally` statement block."},{"pos":[678,686],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[690,804],"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept>","source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)"}]}