<?xml version="1.0"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="try-finally.md" source-language="en-US" target-language="zh-tw">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-0a91294" tool-company="Microsoft" />
      <xliffext:olfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">15111a185f73f60e77139d3a7faef7f32f4bf613</xliffext:olfilehash>
      <xliffext:olfilepath xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">docs\csharp\language-reference\keywords\try-finally.md</xliffext:olfilepath>
      <xliffext:oltranslationpriority xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">vbcs_med-ht</xliffext:oltranslationpriority>
      <xliffext:oltranslationtype xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">HT</xliffext:oltranslationtype>
      <xliffext:olskeletonhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">5823728d7590a750928b7dd1e0decd34878da8d3</xliffext:olskeletonhash>
      <xliffext:olxliffhash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">ac4870a3b54ed01867cd3bca0f7fb6ca2d4719ef</xliffext:olxliffhash>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" restype="x-metadata">
          <source>try-finally - C# Reference</source>
        </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve">
          <source>try-finally (C# Reference)</source>
        </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve">
          <source>By using a <ph id="ph1">`finally`</ph> block, you can clean up any resources that are allocated in a <bpt id="p1">[</bpt>try<ept id="p1">](try-catch.md)</ept> block, and you can run code even if an exception occurs in the <ph id="ph2">`try`</ph> block.</source>
        </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve">
          <source>Typically, the statements of a <ph id="ph1">`finally`</ph> block run when control leaves a <ph id="ph2">`try`</ph> statement.</source>
        </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve">
          <source>The transfer of control can occur as a result of normal execution, of execution of a <ph id="ph1">`break`</ph>, <ph id="ph2">`continue`</ph>, <ph id="ph3">`goto`</ph>, or <ph id="ph4">`return`</ph> statement, or of propagation of an exception out of the <ph id="ph5">`try`</ph> statement.</source>
        </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve">
          <source>Within a handled exception, the associated <ph id="ph1">`finally`</ph> block is guaranteed to be run.</source>
        </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve">
          <source>However, if the exception is unhandled, execution of the <ph id="ph1">`finally`</ph> block is dependent on how the exception unwind operation is triggered.</source>
        </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve">
          <source>That, in turn, is dependent on how your computer is set up.</source>
        </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve">
          <source>Usually, when an unhandled exception ends an application, whether or not the <ph id="ph1">`finally`</ph> block is run is not important.</source>
        </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve">
          <source>However, if you have statements in a <ph id="ph1">`finally`</ph> block that must be run even in that situation, one solution is to add a <ph id="ph2">`catch`</ph> block to the <ph id="ph3">`try`</ph><ph id="ph4">-</ph><ph id="ph5">`finally`</ph> statement.</source>
        </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve">
          <source>Alternatively, you can catch the exception that might be thrown in the <ph id="ph1">`try`</ph> block of a <ph id="ph2">`try`</ph><ph id="ph3">-</ph><ph id="ph4">`finally`</ph> statement higher up the call stack.</source>
        </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve">
          <source>That is, you can catch the exception in the method that calls the method that contains the <ph id="ph1">`try`</ph><ph id="ph2">-</ph><ph id="ph3">`finally`</ph> statement, or in the method that calls that method, or in any method in the call stack.</source>
        </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve">
          <source>If the exception is not caught, execution of the <ph id="ph1">`finally`</ph> block depends on whether the operating system chooses to trigger an exception unwind operation.</source>
        </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve">
          <source>Example</source>
        </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve">
          <source>In the following example, an invalid conversion statement causes a <ph id="ph1">`System.InvalidCastException`</ph> exception.</source>
        </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve">
          <source>The exception is unhandled.</source>
        </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve">
          <source>In the following example, an exception from the <ph id="ph1">`TryCast`</ph> method is caught in a method farther up the call stack.</source>
        </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve">
          <source>For more information about <ph id="ph1">`finally`</ph>, see <bpt id="p1">[</bpt>try-catch-finally<ept id="p1">](try-catch-finally.md)</ept>.</source>
        </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve">
          <source>C# also contains the <bpt id="p1">[</bpt>using statement<ept id="p1">](using-statement.md)</ept>, which provides similar functionality for <ph id="ph1">&lt;xref:System.IDisposable&gt;</ph> objects in a convenient syntax.</source>
        </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve">
          <source>C# language specification</source>
        </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve">
          <source>See also</source>
        </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>C# Reference<ept id="p1">](../index.md)</ept></source>
        </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>C# Programming Guide<ept id="p1">](../../programming-guide/index.md)</ept></source>
        </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>C# Keywords<ept id="p1">](index.md)</ept></source>
        </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>try, throw, and catch Statements (C++)<ept id="p1">](/cpp/cpp/try-throw-and-catch-statements-cpp)</ept></source>
        </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>Exception Handling Statements<ept id="p1">](exception-handling-statements.md)</ept></source>
        </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>throw<ept id="p1">](throw.md)</ept></source>
        </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>try-catch<ept id="p1">](try-catch.md)</ept></source>
        </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve">
          <source><bpt id="p1">[</bpt>How to: Explicitly Throw Exceptions<ept id="p1">](../../../standard/exceptions/how-to-explicitly-throw-exceptions.md)</ept></source>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>